# Aula 15 - Algoritmos e Estrutura de Dados
## Exercícios sobre Numpy

## Fácil

⚫1- Importe numpy como ‘np’ e imprima o número da versão.

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

⚫2- Crie uma matriz 1D com números de 0 a 9

In [ ]:
matriz = np.arange(10)
print(matriz)

[0 1 2 3 4 5 6 7 8 9]


⚫3- Crie uma matriz booleana numpy 3×3 com ‘True’

In [ ]:
print(np.full((3, 3), True, dtype = bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
print(np.ones((3, 3), dtype = bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


⚫4- Extraia todos os números ímpares de uma variável chamada 'arr' que recebe o vetorcriado no exercícios 2 acima.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

⚫5- Substitua todos os números ímpares arr por -1

In [ ]:
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Médio

⚫1- Substitua todos os números ímpares em arr com -1 sem alterar arr

In [1]:
def substituir_impares(arr):
    """
    Substitui todos os números ímpares em arr por -1 sem alterar arr.

    Args:
    arr (list): Lista de números inteiros.

    Returns:
    list: Nova lista com números ímpares substituídos por -1.
    """
    nova_lista = [-1 if x % 2 != 0 else x for x in arr]
    return nova_lista

# Exemplo de uso
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
nova_lista = substituir_impares(arr)
print("Lista original:", arr)
print("Nova lista:", nova_lista)

Lista original: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Nova lista: [-1, 2, -1, 4, -1, 6, -1, 8, -1, 10]


⚫2- Converta uma matriz 1D para uma matriz 2D com 2 linhas:

In [2]:
import numpy as np

def converter_para_matriz_2d(matriz_1d):
    """
    Converte uma matriz 1D em uma matriz 2D com 2 linhas.

    Args:
    matriz_1d (list): Matriz 1D a ser convertida.

    Returns:
    numpy.ndarray: Matriz 2D com 2 linhas.
    """
    # Verifica se o número de elementos na matriz 1D é par
    if len(matriz_1d) % 2 != 0:
        raise ValueError("A matriz 1D deve ter um número par de elementos.")

    # Converte a lista para um array numpy
    array_1d = np.array(matriz_1d)

    # Divide o array em duas partes iguais e redimensiona para uma matriz 2D com 2 linhas
    matriz_2d = np.reshape(array_1d, (2, -1))

    return matriz_2d

# Exemplo de uso
matriz_1d = [1, 2, 3, 4, 5, 6, 7, 8]
matriz_2d = converter_para_matriz_2d(matriz_1d)
print("Matriz 1D:", matriz_1d)
print("Matriz 2D com 2 linhas:")
print(matriz_2d)


Matriz 1D: [1, 2, 3, 4, 5, 6, 7, 8]
Matriz 2D com 2 linhas:
[[1 2 3 4]
 [5 6 7 8]]


⚫3- Empilhe matrizes verticalmente:

In [3]:
import numpy as np

def empilhar_verticalmente(matriz1, matriz2):
    """
    Empilha duas matrizes verticalmente.

    Args:
    matriz1 (numpy.ndarray): Primeira matriz a ser empilhada.
    matriz2 (numpy.ndarray): Segunda matriz a ser empilhada.

    Returns:
    numpy.ndarray: Matriz resultante da concatenação vertical.
    """
    # Empilha as matrizes verticalmente
    matriz_empilhada = np.vstack((matriz1, matriz2))

    return matriz_empilhada

# Exemplo de uso
matriz1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
matriz2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

matriz_empilhada = empilhar_verticalmente(matriz1, matriz2)
print("Matriz 1:")
print(matriz1)
print("\nMatriz 2:")
print(matriz2)
print("\nMatriz empilhada verticalmente:")
print(matriz_empilhada)

Matriz 1:
[[1 2 3]
 [4 5 6]]

Matriz 2:
[[ 7  8  9]
 [10 11 12]]

Matriz empilhada verticalmente:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


⚫4- Empilhe as matrizes horizontalmente:

In [4]:
import numpy as np

def empilhar_horizontalmente(matriz1, matriz2):
    """
    Empilha duas matrizes horizontalmente.

    Args:
    matriz1 (numpy.ndarray): Primeira matriz a ser empilhada.
    matriz2 (numpy.ndarray): Segunda matriz a ser empilhada.

    Returns:
    numpy.ndarray: Matriz resultante da concatenação horizontal.
    """
    # Empilha as matrizes horizontalmente
    matriz_empilhada = np.hstack((matriz1, matriz2))

    return matriz_empilhada

# Exemplo de uso
matriz1 = np.array([[1, 2],
                    [3, 4]])
matriz2 = np.array([[5, 6],
                    [7, 8]])

matriz_empilhada = empilhar_horizontalmente(matriz1, matriz2)
print("Matriz 1:")
print(matriz1)
print("\nMatriz 2:")
print(matriz2)
print("\nMatriz empilhada horizontalmente:")
print(matriz_empilhada)

Matriz 1:
[[1 2]
 [3 4]]

Matriz 2:
[[5 6]
 [7 8]]

Matriz empilhada horizontalmente:
[[1 2 5 6]
 [3 4 7 8]]


⚫5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.

In [6]:
a = np.array([1,2,3])

In [9]:
import numpy as np

def criar_padrao(a):
    """
    Cria o padrão especificado com base na matriz de entrada 'a'.

    Args:
    a (numpy.ndarray): Matriz de entrada.

    Returns:
    numpy.ndarray: Matriz resultante com o padrão criado.
    """
    # Criando uma matriz com o padrão desejado
    n = len(a)
    padrao = np.repeat(a, np.arange(n, 0, -1))

    # Redimensionando para formar o padrão em forma de matriz
    padrao_final = np.zeros((n, n), dtype=int)
    padrao_final[np.triu_indices(n)] = padrao

    return padrao_final

# Definindo a matriz de entrada
a = np.array([1, 2, 3])

# Criando o padrão
resultado = criar_padrao(a)

# Exibindo o resultado
print(resultado)

[[1 1 1]
 [0 2 2]
 [0 0 3]]


## Difícil

⚫1- Calcule as contagens de valores únicos na linha.

In [10]:
import numpy as np

def contar_valores_unicos_por_linha(matriz):
    """
    Calcula as contagens de valores únicos em cada linha da matriz.

    Args:
    matriz (numpy.ndarray): Matriz de entrada.

    Returns:
    numpy.ndarray: Matriz com as contagens de valores únicos por linha.
    """
    # Número de linhas e colunas da matriz
    num_linhas, num_colunas = matriz.shape

    # Inicializa uma matriz para armazenar as contagens de valores únicos por linha
    contagens = np.zeros((num_linhas,))

    # Itera sobre cada linha da matriz
    for i in range(num_linhas):
        # Obtém os valores únicos e suas contagens na linha atual
        valores_unicos, contagem = np.unique(matriz[i], return_counts=True)

        # Soma as contagens de valores únicos na linha atual
        contagens[i] = np.sum(contagem)

    return contagens

# Exemplo de uso
matriz = np.array([[1, 2, 3, 2],
                   [2, 2, 1, 3],
                   [1, 1, 2, 2]])

contagens_por_linha = contar_valores_unicos_por_linha(matriz)
print("Matriz:")
print(matriz)
print("\nContagens de valores únicos por linha:")
print(contagens_por_linha)

Matriz:
[[1 2 3 2]
 [2 2 1 3]
 [1 1 2 2]]

Contagens de valores únicos por linha:
[4. 4. 4.]


In [ ]:
def counts_of_all_values_rowwise(arr2d):
